name: PiraruCooks
options:
  bundleIdPrefix: com.solimoes
packages:
  Parintins:
    url: https://github.com/Rio-Solimoes/Parintins.git
    branch: main
targets:
  PiraruCooks:
    type: application
    platform: iOS
    deploymentTarget: "17.4"
    settings:
      base:
        MARKETING_VERSION: 1.0
    sources:
      - PiraruCooks
    info:
      path: ./PiraruCooks/Info.plist
      properties:
        CFBundleVersion: "1"
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
          ]
        UISupportedInterfaceOrientations~ipad:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationPortraitUpsideDown,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
          ]
        UIAppFonts:
          [
            "KulimPark-ExtraLight.ttf",
            "KulimPark-ExtraLightItalic.ttf",
            "KulimPark-Light.ttf",
            "KulimPark-LightItalic.ttf",
            "KulimPark-Regular.ttf",
            "KulimPark-Italic.ttf",
            "KulimPark-SemiBold.ttf",
            "KulimPark-SemiBoldItalic.ttf",
            "KulimPark-Bold.ttf",
            "KulimPark-BoldItalic.ttf",
          ]
    postCompileScripts:
      - script: |
          if [[ "$(uname -m)" == arm64 ]]; then
              export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftlint > /dev/null; then
            swiftlint .
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: Run SwiftLint
    dependencies:
      - package: Parintins
